<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251216202441 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE direction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, level VARCHAR(255) NOT NULL, points DOUBLE PRECISION NOT NULL, status VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, reviewer_id INT NOT NULL, direction_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3BAE0AA770574616 ON event (reviewer_id)');
        $this->addSql('CREATE INDEX IDX_3BAE0AA7AF73D997 ON event (direction_id)');
        $this->addSql('CREATE TABLE event_student (event_id INT NOT NULL, student_id INT NOT NULL, PRIMARY KEY (event_id, student_id))');
        $this->addSql('CREATE INDEX IDX_3274069C71F7E88B ON event_student (event_id)');
        $this->addSql('CREATE INDEX IDX_3274069CCB944F1A ON event_student (student_id)');
        $this->addSql('CREATE TABLE reviewer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, full_name VARCHAR(255) NOT NULL, institute VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE reviewer_student (reviewer_id INT NOT NULL, student_id INT NOT NULL, PRIMARY KEY (reviewer_id, student_id))');
        $this->addSql('CREATE INDEX IDX_7635E72A70574616 ON reviewer_student (reviewer_id)');
        $this->addSql('CREATE INDEX IDX_7635E72ACB944F1A ON reviewer_student (student_id)');
        $this->addSql('CREATE TABLE student (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, study_group VARCHAR(255) NOT NULL, institute VARCHAR(255) NOT NULL, rating INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA770574616 FOREIGN KEY (reviewer_id) REFERENCES reviewer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7AF73D997 FOREIGN KEY (direction_id) REFERENCES direction (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_student ADD CONSTRAINT FK_3274069C71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_student ADD CONSTRAINT FK_3274069CCB944F1A FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reviewer_student ADD CONSTRAINT FK_7635E72A70574616 FOREIGN KEY (reviewer_id) REFERENCES reviewer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reviewer_student ADD CONSTRAINT FK_7635E72ACB944F1A FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA770574616');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA7AF73D997');
        $this->addSql('ALTER TABLE event_student DROP CONSTRAINT FK_3274069C71F7E88B');
        $this->addSql('ALTER TABLE event_student DROP CONSTRAINT FK_3274069CCB944F1A');
        $this->addSql('ALTER TABLE reviewer_student DROP CONSTRAINT FK_7635E72A70574616');
        $this->addSql('ALTER TABLE reviewer_student DROP CONSTRAINT FK_7635E72ACB944F1A');
        $this->addSql('DROP TABLE direction');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE event_student');
        $this->addSql('DROP TABLE reviewer');
        $this->addSql('DROP TABLE reviewer_student');
        $this->addSql('DROP TABLE student');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
