<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251223175254 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE event ADD reviewer_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA770574616 FOREIGN KEY (reviewer_id) REFERENCES reviewer (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_3BAE0AA770574616 ON event (reviewer_id)');
        $this->addSql('ALTER TABLE student ALTER id DROP IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA770574616');
        $this->addSql('DROP INDEX IDX_3BAE0AA770574616');
        $this->addSql('ALTER TABLE event DROP reviewer_id');
        $this->addSql('ALTER TABLE student ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }
}
